"""Some update

Revision ID: 802ec1e7399d
Revises: b6b932874463
Create Date: 2023-03-21 07:35:59.575793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '802ec1e7399d'
down_revision = 'b6b932874463'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inventory_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_enrolled')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_enrolled', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('inventory_date')

    # ### end Alembic commands ###
