"""Add odoo_id to Products

Revision ID: bf5cd7255fc4
Revises: 51ca3128849e
Create Date: 2023-03-23 16:56:55.105677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf5cd7255fc4'
down_revision = '51ca3128849e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('odoo_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_products_odoo_id'), ['odoo_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_odoo_id'))
        batch_op.drop_column('odoo_id')

    # ### end Alembic commands ###
