"""out_of_stock

Revision ID: bfc970bbdec4
Revises: 295063f05364
Create Date: 2023-03-24 15:50:33.477971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc970bbdec4'
down_revision = '295063f05364'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('out_of_stock', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventories', schema=None) as batch_op:
        batch_op.drop_column('out_of_stock')

    # ### end Alembic commands ###
