"""table update saleable

Revision ID: cd78b7d22aa5
Revises: 047f2af190f2
Create Date: 2023-09-26 04:39:59.724283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd78b7d22aa5'
down_revision = '047f2af190f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_saleable_ampru',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=True),
    sa.Column('int_ref', sa.String(length=64), nullable=True),
    sa.Column('product_name', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('quantity_reserved', sa.Integer(), nullable=True),
    sa.Column('quantity_available', sa.Integer(), nullable=True),
    sa.Column('inventory_date', sa.DateTime(), nullable=True),
    sa.Column('out_of_stock', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products_saleable_ampru')
    # ### end Alembic commands ###
